version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432" # Map port 5432 on the host to port 5432 in the container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: checks-payment-control-service
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: